#ifndef SHADERS_H
#define SHADERS_H

/* ═══════════════════════════════════════════════════════════
   BASIC SHADER — flat colored quads
   ═══════════════════════════════════════════════════════════ */
static const char *basic_vert_src =
    "#version 330 core\n"
    "layout(location=0) in vec2 aPos;\n"
    "uniform mat4 uProjection;\n"
    "uniform mat4 uModel;\n"
    "void main() {\n"
    "    gl_Position = uProjection * uModel * vec4(aPos, 0.0, 1.0);\n"
    "}\n";

static const char *basic_frag_src =
    "#version 330 core\n"
    "out vec4 FragColor;\n"
    "uniform vec4 uColor;\n"
    "void main() {\n"
    "    FragColor = uColor;\n"
    "}\n";

/* ═══════════════════════════════════════════════════════════
   GLOW SHADER — neon glow effect on tetromino blocks
   ═══════════════════════════════════════════════════════════ */
static const char *glow_vert_src =
    "#version 330 core\n"
    "layout(location=0) in vec2 aPos;\n"
    "uniform mat4 uProjection;\n"
    "uniform mat4 uModel;\n"
    "out vec2 vUV;\n"
    "void main() {\n"
    "    vUV = aPos;\n"
    "    gl_Position = uProjection * uModel * vec4(aPos, 0.0, 1.0);\n"
    "}\n";

static const char *glow_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform vec4 uColor;\n"
    "uniform float uIntensity;\n"
    "uniform float uTime;\n"
    "\n"
    "void main() {\n"
    "    vec2 center = vUV - vec2(0.5);\n"
    "    float dist = length(center);\n"
    "    \n"
    "    /* Inner bright core */\n"
    "    float core = smoothstep(0.5, 0.1, dist);\n"
    "    \n"
    "    /* Outer glow ring */\n"
    "    float glow = exp(-dist * 3.0) * uIntensity;\n"
    "    \n"
    "    /* Pulsing effect */\n"
    "    float pulse = 0.85 + 0.15 * sin(uTime * 2.5);\n"
    "    \n"
    "    /* Edge highlight (border glow) */\n"
    "    float edge = smoothstep(0.48, 0.42, dist) - smoothstep(0.42, 0.35, dist);\n"
    "    edge *= 0.6;\n"
    "    \n"
    "    /* Inner gradient — darker center for depth */\n"
    "    float inner = smoothstep(0.0, 0.35, dist) * 0.3;\n"
    "    \n"
    "    vec3 baseColor = uColor.rgb;\n"
    "    vec3 brightColor = mix(baseColor, vec3(1.0), 0.5);\n"
    "    \n"
    "    vec3 color = baseColor * (core * 0.7 + inner) * pulse;\n"
    "    color += brightColor * edge * pulse;\n"
    "    color += baseColor * glow * pulse * 0.5;\n"
    "    \n"
    "    /* Scanline effect */\n"
    "    float scanline = 0.95 + 0.05 * sin(gl_FragCoord.y * 1.5 + uTime * 3.0);\n"
    "    color *= scanline;\n"
    "    \n"
    "    float alpha = max(core, glow * 0.5) * uColor.a;\n"
    "    FragColor = vec4(color, alpha);\n"
    "}\n";

/* ═══════════════════════════════════════════════════════════
   PARTICLE SHADER — additive blended particles
   ═══════════════════════════════════════════════════════════ */
static const char *particle_vert_src =
    "#version 330 core\n"
    "layout(location=0) in vec2 aPos;\n"
    "uniform mat4 uProjection;\n"
    "uniform mat4 uModel;\n"
    "out vec2 vUV;\n"
    "void main() {\n"
    "    vUV = aPos;\n"
    "    gl_Position = uProjection * uModel * vec4(aPos, 0.0, 1.0);\n"
    "}\n";

static const char *particle_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform vec4 uColor;\n"
    "uniform float uAlpha;\n"
    "\n"
    "void main() {\n"
    "    vec2 center = vUV - vec2(0.5);\n"
    "    float dist = length(center);\n"
    "    float soft = exp(-dist * 6.0);\n"
    "    FragColor = vec4(uColor.rgb * 1.5, soft * uAlpha);\n"
    "}\n";

/* ═══════════════════════════════════════════════════════════
   BACKGROUND SHADER — theme-aware animated grid background
   ═══════════════════════════════════════════════════════════ */
static const char *bg_vert_src =
    "#version 330 core\n"
    "layout(location=0) in vec2 aPos;\n"
    "out vec2 vUV;\n"
    "void main() {\n"
    "    vUV = aPos;\n"
    "    gl_Position = vec4(aPos * 2.0 - 1.0, 0.0, 1.0);\n"
    "}\n";

static const char *bg_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform float uTime;\n"
    "uniform vec2  uResolution;\n"
    "uniform vec3  uBgTop;\n"
    "uniform vec3  uBgBot;\n"
    "uniform vec3  uAccent;\n"
    "uniform float uScanStr;\n"
    "uniform vec3  uPieceColors[7];\n"
    "uniform float uMode3D;\n"
    "\n"
    "/* ── Hash for pseudo-random ── */\n"
    "float hash21(vec2 p) {\n"
    "    p = fract(p * vec2(123.34, 456.21));\n"
    "    p += dot(p, p + 45.32);\n"
    "    return fract(p.x * p.y);\n"
    "}\n"
    "\n"
    "/* Tetromino shapes: 16-bit bitmask per piece (4x4 grid, MSB = top-left) */\n"
    "/*   I=3840  O=26112  T=19968  S=27648  Z=50688  J=36352  L=11776   */\n"
    "bool cellFilled(int tt, int cx, int cy) {\n"
    "    if (cx < 0 || cx > 3 || cy < 0 || cy > 3) return false;\n"
    "    int s[7] = int[7](3840, 26112, 19968, 27648, 50688, 36352, 11776);\n"
    "    int bit = cy * 4 + cx;\n"
    "    return ((s[tt] >> (15 - bit)) & 1) != 0;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 uv = vUV;\n"
    "    float aspect = uResolution.x / uResolution.y;\n"
    "\n"
    "    /* ── Base gradient ── */\n"
    "    vec3 color = mix(uBgBot, uBgTop, uv.y);\n"
    "\n"
    "    /* ── Scrolling grid lines ── */\n"
    "    vec2 grid = fract(uv * vec2(30.0, 20.0) + vec2(0.0, uTime * 0.05));\n"
    "    float gridLine = smoothstep(0.02, 0.0, grid.x) + smoothstep(0.02, 0.0, grid.y);\n"
    "    color += uAccent * gridLine * 0.12;\n"
    "\n"
    "    /* ── Falling tetromino blocks — 5 depth layers ── */\n"
    "    for (int layer = 0; layer < 5; layer++) {\n"
    "        float fl = float(layer);\n"
    "        float depth = 0.2 + fl * 0.2;\n"
    "        float speed = 0.02 + depth * 0.04;\n"
    "        float layerAlpha = 0.06 + depth * 0.12;\n"
    "        float cellSz = 0.015 + depth * 0.012;\n"
    "\n"
    "        /* Perspective convergence — farther layers contract toward center */\n"
    "        float conv = (1.0 - depth) * 0.3;\n"
    "        vec2 pUV = (uv - 0.5) * (1.0 + conv) + 0.5;\n"
    "        pUV.x *= aspect;\n"
    "\n"
    "        /* Grid of 4x4 tetromino blocks */\n"
    "        float blockSz = cellSz * 4.0;\n"
    "        vec2 gUV = pUV / blockSz;\n"
    "        gUV.y -= uTime * speed;\n"
    "\n"
    "        /* Stagger columns for natural feel */\n"
    "        float col = floor(gUV.x);\n"
    "        gUV.y += hash21(vec2(col, fl * 7.13)) * 40.0;\n"
    "\n"
    "        vec2 blockID  = floor(gUV);\n"
    "        vec2 blockFrac = fract(gUV);\n"
    "\n"
    "        /* Sparsity — only ~20%% of grid slots hold a block */\n"
    "        float vis = hash21(blockID + fl * 97.0);\n"
    "        if (vis > 0.20) continue;\n"
    "\n"
    "        /* Tetromino type (0-6) */\n"
    "        int tt = int(floor(hash21(blockID * 3.17 + fl * 53.0) * 7.0));\n"
    "        tt = clamp(tt, 0, 6);\n"
    "\n"
    "        /* Cell within 4x4 tetromino */\n"
    "        ivec2 cell = ivec2(floor(blockFrac * 4.0));\n"
    "        if (!cellFilled(tt, cell.x, cell.y)) continue;\n"
    "\n"
    "        /* UV within this cell [0,1] */\n"
    "        vec2 cUV = fract(blockFrac * 4.0);\n"
    "\n"
    "        /* ── Rounded-rect SDF mask ── */\n"
    "        float pad   = 0.1;\n"
    "        float round = 0.06;\n"
    "        vec2  d     = abs(cUV - 0.5) - (0.5 - pad - round);\n"
    "        float sdf   = length(max(d, 0.0)) - round;\n"
    "        float mask  = smoothstep(0.02, -0.02, sdf);\n"
    "\n"
    "        /* Neon edge glow */\n"
    "        float edgeGlow = smoothstep(0.04, 0.0, abs(sdf)) * 0.8;\n"
    "\n"
    "        /* Inner depth for 3D feel */\n"
    "        float inner = smoothstep(0.0, 0.25, length(cUV - 0.5)) * 0.25;\n"
    "\n"
    "        /* Shiny diagonal sweep */\n"
    "        float sweepPh = (cUV.x + cUV.y) * 2.0\n"
    "                      + uTime * 0.8 + hash21(blockID) * 6.2832;\n"
    "        float shine = pow(max(0.0, sin(sweepPh)), 8.0) * 0.5;\n"
    "\n"
    "        /* Specular highlight (top-left catch light) */\n"
    "        float spec = exp(-length(cUV - vec2(0.28, 0.28)) * 6.0) * 0.35;\n"
    "\n"
    "        /* Piece color from theme */\n"
    "        vec3 pc     = uPieceColors[tt];\n"
    "        vec3 bright = mix(pc, vec3(1.0), 0.4);\n"
    "\n"
    "        /* 3D extrusion effect */\n"
    "        vec3 extrusionCol = vec3(0.0);\n"
    "        if (uMode3D > 0.05) {\n"
    "            float extD = uMode3D * 0.12;\n"
    "            for (int ei = 3; ei >= 1; ei--) {\n"
    "                float ef = float(ei) * extD;\n"
    "                vec2 eCUV = cUV + vec2(ef, -ef);\n"
    "                vec2 eD = abs(eCUV - 0.5) - (0.5 - pad - round);\n"
    "                float eSdf = length(max(eD, 0.0)) - round;\n"
    "                float eMask = smoothstep(0.02, -0.02, eSdf);\n"
    "                float shade = 0.15 + 0.1 * (1.0 - float(ei) / 4.0);\n"
    "                extrusionCol += pc * shade * eMask * uMode3D;\n"
    "            }\n"
    "            float topEdge = smoothstep(0.5 - pad, 0.5 - pad - 0.08, cUV.y) * mask;\n"
    "            extrusionCol += bright * topEdge * 0.3 * uMode3D;\n"
    "            float rightEdge = smoothstep(0.5 - pad, 0.5 - pad - 0.06, 1.0 - cUV.x) * mask;\n"
    "            extrusionCol += pc * 0.05 * rightEdge * uMode3D;\n"
    "        }\n"
    "\n"
    "        /* Composite */\n"
    "        vec3 blockCol = pc * mask * (0.6 + inner)\n"
    "                      + bright * edgeGlow\n"
    "                      + vec3(1.0) * shine * mask\n"
    "                      + bright * spec  * mask\n"
    "                      + extrusionCol;\n"
    "\n"
    "        /* Depth-modulated fade with slow pulse */\n"
    "        float fade = layerAlpha * (0.7 + 0.3 * sin(uTime * 0.5 + fl * 1.2));\n"
    "        color += blockCol * fade;\n"
    "    }\n"
    "\n"
    "    /* ── Horizontal scan line ── */\n"
    "    float scan = smoothstep(0.01, 0.0, abs(fract(uv.y - uTime * 0.1) - 0.5) - 0.498);\n"
    "    color += uAccent * 3.0 * scan * 0.1;\n"
    "\n"
    "    /* ── Vignette ── */\n"
    "    float vignette = 1.0 - length((uv - 0.5) * 1.3);\n"
    "    vignette = smoothstep(0.0, 0.7, vignette);\n"
    "    color *= vignette;\n"
    "\n"
    "    /* ── CRT scanlines ── */\n"
    "    float scanlines = 1.0 - uScanStr * 0.08 * (1.0 - sin(gl_FragCoord.y * 2.0));\n"
    "    color *= scanlines;\n"
    "\n"
    "    /* ── Subtle noise flicker ── */\n"
    "    float noise = fract(sin(dot(uv + uTime, vec2(12.9898, 78.233))) * 43758.5453);\n"
    "    color += noise * 0.008;\n"
    "\n"
    "    FragColor = vec4(color, 1.0);\n"
    "}\n";

/* ═══════════════════════════════════════════════════════════
   POST-PROCESSING — Fullscreen vertex shader (shared)
   Uses bg_vert_src — maps [0,1] quad to NDC, passes vUV
   ═══════════════════════════════════════════════════════════ */

/* ─── BRIGHT PASS — extract pixels above brightness threshold ─── */
static const char *bright_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D uScene;\n"
    "uniform float uThreshold;\n"
    "\n"
    "void main() {\n"
    "    vec4 c = texture(uScene, vUV);\n"
    "    float brightness = dot(c.rgb, vec3(0.2126, 0.7152, 0.0722));\n"
    "    FragColor = brightness > uThreshold ? c : vec4(vec3(0.0), 1.0);\n"
    "}\n";

/* ─── GAUSSIAN BLUR — separable 9-tap blur ─── */
static const char *blur_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D uImage;\n"
    "uniform vec2 uDirection;\n"
    "\n"
    "void main() {\n"
    "    float w[5] = float[](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);\n"
    "    vec3 result = texture(uImage, vUV).rgb * w[0];\n"
    "    for (int i = 1; i < 5; i++) {\n"
    "        result += texture(uImage, vUV + uDirection * float(i)).rgb * w[i];\n"
    "        result += texture(uImage, vUV - uDirection * float(i)).rgb * w[i];\n"
    "    }\n"
    "    FragColor = vec4(result, 1.0);\n"
    "}\n";

/* ─── COMPOSITE — blend original scene with bloom texture ─── */
static const char *composite_frag_src =
    "#version 330 core\n"
    "in vec2 vUV;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D uScene;\n"
    "uniform sampler2D uBloom;\n"
    "uniform float uBloomStr;\n"
    "\n"
    "void main() {\n"
    "    vec3 scene = texture(uScene, vUV).rgb;\n"
    "    vec3 bloom = texture(uBloom, vUV).rgb;\n"
    "    vec3 result = scene + bloom * uBloomStr;\n"
    "    /* Subtle tone mapping to prevent harsh clipping */\n"
    "    result = result / (result + vec3(1.0));\n"
    "    /* Gamma correct for smoother look */\n"
    "    result = pow(result, vec3(1.0 / 1.1));\n"
    "    FragColor = vec4(result, 1.0);\n"
    "}\n";

#endif /* SHADERS_H */
